// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectOCR.DataLayer;

#nullable disable

namespace projectOCR.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20241203163707_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projectOCR.Models.Image", b =>
                {
                    b.Property<int>("resimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("resimId"));

                    b.Property<string>("resimAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resimUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("resimId");

                    b.ToTable("İmageTable");
                });
#pragma warning restore 612, 618
        }
    }
}
